[package]
name = "toy-cv"
version = "0.0.0"
compiler = "0.13.1"
entrypoint = "scr/lib.typ"
repository = "https://github.com/ToyHugs/toy-cv"
authors = ["Pierre GUYOT <@toyhugs>"]
license = "MIT-0"
description = "✨ A CV and cover letter template"
keywords = ["CV", "resume", "cover letter"]
exclude = ["previews/", "*.pdf"]
categories = ["cv"]
disciplines = []


[template]
path = "templates"
entrypoint = "cv.typ"
thumbnail = "thumbnail.png"
